### ISSUE TITLE
Add ignore files feature

### ISSUE THREAD

**Issue by Maatteogekko** [gmlewis/go-flutter-stylizer#2]
I don't want to stylize `build_runner` generated files, because when they are generated again they are unnecessarily counted as modified files by `git`. 
Would you consider adding a flag or config file to list files and globs to ignore?

**Comment by gmlewis** [comment]
> Would you consider adding a flag or config file to list files and globs to ignore?

That sounds like a nice feature to add. Do you have a preference or a favorite glob style or favorite command you would like to emulate? I ask because there are an unlimited number of ways that this could be implemented, and if you are familiar with something it might be best to start there.

**Comment by Maatteogekko** [comment]
I would say that using the same syntax used in `analysis_options.yaml` would be good because flutter developers would be already accustomed to it.
This is what they use: https://pub.dev/packages/glob#syntax
Maybe creating something like `flutter-stylizer.yaml` would be even better, with something like this inside:
```yaml
exclude:
  - "**/*.g.dart"
  - "**/*.gr.dart"
  - "**/*.freezed.dart"
```

**Comment by gmlewis** [comment]
@Maatteogekko - please try out the `v0.1.4` release and see if this implements what you asked for:
https://github.com/gmlewis/go-flutter-stylizer/releases/tag/v0.1.4

**Comment by Maatteogekko** [comment]
Works like a charm! 💯 
Thank you for the nice addition in so little time. Keep up the great work! 💪🏻
