### ISSUE TITLE
Is there a way to sort public methods and then private methods?

### ISSUE THREAD

**Issue by longtimedeveloper** [gmlewis/go-flutter-stylizer#3]
Hi,

Such an outstanding Extension for developers, thank you!

Is there a way to sort public methods and then private methods?

I'm hoping that all my private methods would be sorted below public methods.

**Code file example methods:**

`myMethod(){};`
`_myMethod(){};`

**Current sorting results in:**
`_myMethod(){};`
`myMethod(){};`

**Desired sorting results:**
`myMethod(){};`
`_myMethod(){};`

Thank you!  Karl

**Comment by gmlewis** [comment]
> Such an outstanding Extension for developers, thank you!

Thank you for the kind words, @longtimedeveloper !
 
> Is there a way to sort public methods and then private methods?

The extension currently doesn't distinguish between public and private methods, but that seems like a nice enhancement.
I'll see what I can do.

**Comment by longtimedeveloper** [comment]
@gmlewis Splendid.

Best regards and thank you!!

**Comment by gmlewis** [comment]
@longtimedeveloper - please try out version `v0.1.5`: https://github.com/gmlewis/go-flutter-stylizer/releases/tag/v0.1.5

I tried it out with this config file:

```$ cat flutter-stylizer.yaml 
groupAndSortGetterMethods: false
memberOrdering:
  public-constructor
  public-override-methods
  private-other-methods
  public-other-methods
  named-constructors
  public-static-variables
  public-instance-variables
  public-override-variables
  private-static-variables
  private-instance-variables
  build-method
sortOtherMethods: false

exclude:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "**/*.gr.dart"
```

on this source file:

```
$ cat ex.dart
class MyClass {
  myMethod(){};

  _myMethod(){};
}
```

and got this:

```
$ flutter-stylizer -d --config flutter-stylizer.yaml ex.dart 
Using config file: flutter-stylizer.yaml
2021/12/12 16:52:45 Stylizing 1 files...

diff original/ex.dart stylized/ex.dart
--- original/ex.dart
+++ stylized/ex.dart
@@ -1,6 +1,6 @@
 class MyClass {
+  _myMethod(){};
+
   myMethod(){};
-
-  _myMethod(){};
 }
 

Error: Differences were found. Exit code 1.
```

Please let me know if you have any problems with it.

**Comment by longtimedeveloper** [comment]
@gmlewis I'm on Windows and downloaded the installer exe.

I can't figure out what to do with the installer.

What command do I need to issue?

I've read the readme, but not having any success.  I normally install from the Extension marketplace.

Thank you!

**Comment by longtimedeveloper** [comment]
@gmlewis I'm just now noticing that this repo is for a command line tool.  

I use the VS Code Extension version here:  https://github.com/gmlewis/flutter-stylizer

Is it possible to update the VS Code Extension with this change?

**Comment by longtimedeveloper** [comment]
@gmlewis My apologies, I didn't know I filed this request on the wrong repo.

**Comment by gmlewis** [comment]
> @gmlewis My apologies, I didn't know I filed this request on the wrong repo.

No problem, @longtimedeveloper - yes, this repo is the stand-alone version.
Hopefully tomorrow I can implement this change in the actual VSCode extension, which is the other repo. :smile:

**Comment by longtimedeveloper** [comment]
@gmlewis thank you very much.  I have a workaround for now.  I cut the public functions out, run the current stylizer, and paste the public functions back in where I need them.  LOL.  Best regards, Karl

**Comment by gmlewis** [comment]
@longtimedeveloper - the VSCode `flutter-stylizer` extension has now been updated to `0.1.5` and should now behave the same way I described above.

https://marketplace.visualstudio.com/items?itemName=gmlewis-vscode.flutter-stylizer

Please let me know if you have any problems with it.

**Comment by longtimedeveloper** [comment]
@gmlewis thank you for the Christmas gift and for such a quick turnaround on the feature request!!  Best regards, Karl

**Comment by longtimedeveloper** [comment]
@gmlewis works perfectly!!! Thanks again!
