### ISSUE TITLE
failed to correctly move this field init 

### ISSUE THREAD

**Issue by gslender** [gmlewis/go-flutter-stylizer#6]
The current release failed to order this field correctly....

```
 final Map<String, dynamic> _initialValues = kReleaseMode
      ? {}
      : {
          'hubType': 'test',
          'ht.localIP': '192.168.1.1',
          'ht.makerAppID': '2233',
          'ht.accessToken': '7de3-yyyyyy-xxxxxxxxxxx',
        };
```

**Comment by gmlewis** [comment]
@gslender - this should be fixed now in the latest release:
https://github.com/gmlewis/go-flutter-stylizer/releases/tag/v0.1.11

Please try it out and let me know if there are still any issues with it.

Thank you for the report, and I apologize for the bug.

**Comment by gslender** [comment]
Yes fixed. Issue can be closed. Great work :-)
